ALTER TABLE Users 
ADD Status NVARCHAR(20) DEFAULT 'Active' NOT NULL;

ALTER TABLE Borrowings DROP CONSTRAINT FK__Borrowing__UserI__5070F446;
ALTER TABLE Borrowings 
ADD CONSTRAINT FK_Borrowing_User_Cascade 
FOREIGN KEY (UserID) REFERENCES Users(UserID) 
ON DELETE CASCADE;
